### ISSUE TITLE
How to distinguish from sync iterators at runtime?

### ISSUE THREAD

**Issue by dyoder** [zenparsing/async-iteration#10]
How would we determine the protocol for an iterator at runtime? Since these protocols, as far as I'm aware, are not first-class entities, we cannot test whether a given object supports a protocol except via duck-typing. If that's the case, an async iterator may have an identical interface to a synchronous iterator and there would thus be no way to distinguish them without actually calling `next`.

Put another way, if we define a function `isIterator`:

```javascript
function isIterator (it) { 
  return it != undefined && it.next != undefined && it.next.constructor === Function 
}
```

how would we write `isAsyncIterator`?

**Comment by zenparsing** [comment]
@dyoder Good question.

Sync iterators really require the `Symbol.iterator` method in order to be fully compatible with `for-of`.  Likewise, async iterators should have a `Symbol.asyncIterator` method.  One option would be to add a check in `isAsyncIterator` for the `Symbol.asyncIterator` method.

**Comment by dyoder** [comment]
@zenparsing That is the _iterable_, right? I'm assuming in this scenario that we have an iterator object and we don't know where it came from. Example: it's been passed into a function that takes an iterator. Such a function could assume that it's iterators are synchronous (or asynchronous). But if it wanted to check, or to implement different behavior depending on whether the iterator was synchronous or asynchronous, how would it do that?

Or am I misunderstanding something? Perhaps the idea is to rely on the language constructs to provide such variance, opaque to the developer?

**Comment by zenparsing** [comment]
In ES, iterators are iterable.  : )

For iterators, the `Symbol.iterator` method just returns the `this` value.

The for-of statement always looks for `Symbol.iterator`, so in order to be usable by for-of, all iterators really need to implement it.  For example, this results in an error because `iter` doesn't have a `Symbol.iterator` method:

```js
var iter = { next() { return { value: 5, done: false } } };
for (var x of iter) console.log(x)
```

**Comment by dyoder** [comment]
Ah, I see. I had missed that little detail. :)

So we can just check for `Symbol.asyncIterator` as you said above.

**Comment by dyoder** [comment]
Oh, and thanks for the clarification.
