### ISSUE TITLE
Calling return or throw on paused async generator

### ISSUE THREAD

**Issue by zenparsing** [zenparsing/async-iteration#5]
Consider:

```js
async function* agf() {
    try { await new Promise(_=> null) }
    catch (x) { print("caught error") }
    finally { print("finally!") }
}

var ag = agf();
ag.next();
ag.return();
```

What should happen in this case?  The generator is waiting infinitely on a never-resolved promise.  Should "return" and "throw" resume the generator even though it is paused on an await?  It seems like it should.

**Comment by zenparsing** [comment]
I think the answer must be no, at least for "throw".  If we have:


```js
try { await somethingAsync() }
catch (x) { }
```

Then we must be able to assume that `x` arose as a result of the evaluation of `somethingAsync()`, and nothing else.

That leaves "return"...

**Comment by domenic** [comment]
I agree the answer should be no in both cases.

I think both next() and throw() should return promises that are pending forever, to signal that they never get a chance to execute.

**Comment by jedwards1211** [comment]
@domenic in light of #126 I don't get this.  I don't see anything in the spec for `return` and `throw` that says they must resolve or reject after all promises returned by prior calls to `next`?

To me it would be more reasonable if we add a clarification to the async iterator protocol that pending promises from `next` should reject when `return` or `throw` is called.  This would solve a lot or problems with cleanup -- would it cause any new problems?
