### ISSUE TITLE
What happens when yielding a promise?

### ISSUE THREAD

**Issue by bterlson** [zenparsing/async-iteration#8]
From the example:

```js
async function *readLines(path) {

    let file = await fileOpen(path);

    try {

        while (!file.EOF)
            yield await file.readLine();

    } finally {

        await file.close();
    }
}
```

It seems like we could get away with simply yielding the promise thanks to promise unwrapping behavior rather than yielding the result of await. Is this true? Or what am I misunderstanding?

**Comment by domenic** [comment]
Yielding a promise would give `Promise<{ value: Promise<T>, done: boolean }` instead of `Promise<{ value: T, done: boolean }>`, IIUC.

**Comment by bterlson** [comment]
I think you're right. This is interesting to compare with Async Functions which, if you return a promise, the promise is unwrapped... eg.

```js
async function foo() { return Promise.resolve(42) };
foo().then(v => assert(v === 42))

async function* foo() { return Promise.resolve(42) };
let iter = foo();
iter.next().then(function(res) {
  res.value.then(v => assert(v === 42));
});
```

It might be nice to unwrap promises yielded from async generator bodies. Why would this be a bad idea?

**Comment by zenparsing** [comment]
Right, currently yielding and awaiting are orthogonal:  you can yield a promise and it will appear as a promise in the "value" property of the eventual iteration result.

I suppose it could be arranged so that within an async generator function we implicitly perform an await on the the value being yielded.  Alternatively, the async for-of statement could unwrap the "value" property after unwrapping the iteration result.

I haven't had time to think through the implications, though...

**Comment by zenparsing** [comment]
@bterlson That's a great point.

**Comment by domenic** [comment]
I feel the orthogonality is cleaner but I do admit that coming up with use cases for async-iterables-of-promises basically reduces down to coming up with use cases for promises-for-promises, which as we know are verboten.

**Comment by bterlson** [comment]
I agree @Domenic, I think it's morally equivalent to promise-for-promise. Another argument for unwrapping yielded promises is that it will be very common and `yield await` is subtle and likely confusing.

**Comment by zenparsing** [comment]
I agree with this.  Thanks @bterlson !

Also, consider the following case:

```js
async function af() { throw new Error("oops") }

async function* agf() {
    yield af();
}

let iter = agf();
let result = await iter.next();
```

We would certainly (I think) expect `await iter.next()` to throw, instead of returning an iteration result with a rejected promise for a value.

**Comment by benjamn** [comment]
:+1: to awaiting `yield`ed values. I am particularly compelled by the argument that `return` unwraps `Promise`s in `async` functions, and `return` is a lot like `yield`. And of course you can still find a way to smuggle a `Promise` out of an async generator function if you really want to—just hide it in a wrapper object and `yield` that object.

**Comment by benjamn** [comment]
Fixed in Regenerator: https://github.com/facebook/regenerator/commit/37b154955334675318c2346e7e73af460ffce087

**Comment by bman654** [comment]
FWIW I was just trying to figure out why this async code was not working correctly (compiled via babel):

```javascript
var foo = async function Foo() {
    try {
        await Promise.reject(new Error("rejected"));
        console.log("this line should never be reached");
    }
    catch (err) {
        console.log(`error: ${err}`);
    }
}

foo();
```

The trouble is that the `this line should never be reached` was running instead of the catch clause.

I traced it down to the very code you just changed.  If I apply your change to my runtime then the above code works correctly.

**Comment by benjamn** [comment]
Interesting. What version of Babel are you using?

**Comment by bman654** [comment]
babel-core: 5.2.15.
babel-runtime: 5.5.5.

**Comment by benjamn** [comment]
I believe babel-core 5.5.3 is the version you need to guarantee Regenerator 0.8.28 or better. The version of Regenerator you're using simply translates `await x` to `yield x`, whereas the runtime you're using expects `await x` to be translated to `yield regeneratorRuntime.awrap(x)`. The change I mentioned above fixes the immediate problem, now that `yield x` is effectively the same as `yield await x`, but I would still recommend upgrading to the latest runtime!

**Comment by masaeedu** [comment]
@domenic Could you elaborate on why promises-for-promises are verboten? It's probably too late now to revisit this, but I would imagine the behavior that causes the least surprise is the one that does the least amount of magic. In particular, when using a type system like TypeScript, it becomes hard to express exactly what it is the function is returning.

**Comment by domenic** [comment]
No, I'd rather not get off-topic in this repository. You can peruse previous es-discuss threads, TC39 meeting notes, or perhaps the promises-aplus GitHub organization.
